### ISSUE TITLE
Does knit allow target/dependency filenames to contain whitespace?

### ISSUE THREAD

**Issue by vergenzt** [zyedidia/knit#3]
See title. 🙂 This has been one source of annoyance for me using `make` for some projects. (Further reading: https://stackoverflow.com/a/17969578/718180)

**Comment by zyedidia** [comment]
You can have spaces in targets or prerequisites, but they need to be escaped somehow, either by using a backslash, or with quotes. Note that the name of the target will still have the escape character or quotes in it (this is nice because they are still necessary for escaping the spaces for the command)

```lua
return b{
    $ foo\ bar:B:
        touch $output.txt
}
```

```
$ knit
touch foo\ bar.txt
```

```lua
return b{
    $ "foo bar":B:
        touch $output.txt
}
```

```
$ knit
touch "foo bar".txt
```
